export const MAX_VIDEO_AGE = 60 * 60 * 24 * 14; // 14 days
export const MAX_PLAYLIST_VIDEOS_PAGE = 3; // up to 300

export const YOUTUBEI_PROVIDER = "YOUTUBEI_PROVIDER";
export const YOUTUBEI_MUSIC_PROVIDER = "YOUTUBEI_MUSIC_PROVIDER";
